.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...

.. regreg
.. _`regreg github`: http://github.com/regreg/regreg
.. _regreg pypi: http://pypi.python.org/pypi/regreg
.. _regreg issues: http://github.com/regreg/regreg/issues

.. Documentation tools
.. _graphviz: http://www.graphviz.org/
.. _Sphinx: http://sphinx.pocoo.org/
.. _`Sphinx reST`: http://sphinx.pocoo.org/rest.html
.. _reST: http://docutils.sourceforge.net/rst.html
.. _docutils: http://docutils.sourceforge.net

.. Licenses
.. _GPL: http://www.gnu.org/licenses/gpl.html
.. _BSD: http://www.opensource.org/licenses/bsd-license.php
.. _LGPL: http://www.gnu.org/copyleft/lesser.html
.. _MIT License: http://www.opensource.org/licenses/mit-license.php

.. Working process
.. _github: http://github.com

.. Code support stuff
.. _pychecker: http://pychecker.sourceforge.net/
.. _pylint: http://www.logilab.org/project/pylint
.. _pyflakes: http://divmod.org/trac/wiki/DivmodPyflakes
.. _virtualenv: http://pypi.python.org/pypi/virtualenv
.. _git: http://git-scm.com/
.. _doctest-mode: http://www.cis.upenn.edu/~edloper/projects/doctestmode/
.. _nose: http://somethingaboutorange.com/mrl/projects/nose
.. _`python coverage tester`: http://nedbatchelder.com/code/modules/coverage.html

.. Other python projects
.. _numpy: http://www.scipy.org/NumPy
.. _scipy: http://www.scipy.org
.. _cython: http://www.cython.org/
.. _ipython: http://ipython.org
.. _jupyter: http://jupyter.org
.. _matplotlib: http://matplotlib.org
.. _python: http://www.python.org
.. General software
.. _gcc: http://gcc.gnu.org
.. _xcode: http://developer.apple.com/TOOLS/xcode
.. _mingw: http://www.mingw.org
.. _macports: http://www.macports.org/

.. vim: ft=rst
